task_distribution:
  bring_single: 0.7
  bring_pair: 0.0
  clear_receptacle: 0.3

object_distribution:
  water_bottle: 0.4
  apple: 0.3
  book: 0.3

surface_distribution:
  kitchen_counter: 0.4
  dining_table: 0.3
  study_table: 0.3

object_source_distribution:
  water_bottle:
    kitchen_counter: 0.85
    dining_table: 0.10
    study_table: 0.05
  apple:
    kitchen_counter: 0.10
    dining_table: 0.85
    study_table: 0.05
  book:
    kitchen_counter: 0.05
    dining_table: 0.10
    study_table: 0.85
